FROM alpine:latest

USER root

ENV CCACHE_DIR="/src/.ccache-docker"
ENV CCACHE_COMPRESS="true"
ENV CCACHE_COMPRESSLEVEL="5"
ENV CCACHE_MAXSIZE="1000M"

RUN apk update && apk upgrade
RUN apk add -u "cmake>3.30.0" "gcc>14.1.0" "g++>14.1.0" "ninja-is-really-ninja>1.12.0" bash git ccache doxygen py3-jinja2 lcov python3 py3-pip
RUN rm /var/cache/apk/*

WORKDIR /src
