
name: Configure, Build, and Test

on: push

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure, Build, and Tests
      working-directory: ${{github.workspace}}/tests
      run: cmake --workflow --preset ${{env.BUILD_TYPE}}
