
name: Configure, Build, and Test

on: push

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: CPM Cache
      uses: actions/cache@v3
      with:        
        path: ./external
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./external/*') }}

    - name: Configure
      run: cmake -S ${{github.workspace}}/tests -B ${{github.workspace}}/build/tests_${{env.BUILD_TYPE}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build/tests_${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build/tests_${{env.BUILD_TYPE}}
      run: ctest

    - name: Code Coverage - Generation
      uses: danielealbano/lcov-action@v3
      with:
        gcov_path: /usr/bin/gcov-9
        remove_patterns: 3rdparty,tests

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4      
      with:
        files: ${{github.workspace}}/coverage.info
        token: ${{secrets.CODECOV_TOKEN}}
